[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 800
optimizer = true

[invariant]
fail_on_revert = false

[rpc_endpoints]
celo_mainnet = "${MAINNET_RPC_URL}"
celo_alfajores = "${ALFAJORES_RPC_URL}"

# [etherscan]
# unknown_chain = { key = "${TENDERLY_ACCESS_KEY}",       
#                         chain = 42220, url = "" }